### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Much-IqbalFauzi** [femmerling/himakomsi-workshop#2]
mas saya masih beginner, mau tanya, kalau mau buat yang sudah akses ke db gimana? apakah kalau pakai framework flask juga bisa?

**Comment by femmerling** [comment]
@zipeco kalau untuk akses ke Db bisa pakai extension flask-sqlalchemy, bisa lihat di https://flask-sqlalchemy.palletsprojects.com/en/2.x/ untuk dokumentasi lengkapnya
